# Generated by Django 5.2.1 on 2025-06-23 09:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0012_attendance'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feerecord',
            name='payment_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='feerecord',
            name='payment_method',
            field=models.CharField(blank=True, choices=[('cash', 'Cash'), ('card', 'Credit/Debit Card'), ('bank', 'Bank Transfer'), ('upi', 'UPI Payment'), ('other', 'Other')], default='', max_length=50),
        ),
    ]
