# Generated by Django 5.2.1 on 2025-06-25 05:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0015_alter_attendance_options_classroom_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='attendance',
            unique_together={('student', 'subject', 'date')},
        ),
        migrations.RemoveField(
            model_name='attendance',
            name='classroom',
        ),
        migrations.DeleteModel(
            name='Classroom',
        ),
    ]
